# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm run lint'
  displayName: 'Lint code'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'
  displayName: 'Run unit tests'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run e2e'
  displayName: 'Run end-to-end tests'

- task: CmdLine@2
  inputs:
    script: 'ng build --prod'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

